### ISSUE TITLE
Start Playlist instead of Track

### ISSUE THREAD

**Issue by beatpaul** [ebaauw/homebridge-music#4]
Hi!

Any Chance you implement the possibility to start a certain Playlist instead of a certain track?

thanx for you work!!

**Comment by ebaauw** [comment]
I won't be adding playlist support to homebridge-music, but homebridge-music supports any music player that can be controlled through Applescript.  It's easy to create another Applescript script that plays a playlist instead of a track.  These scripts install to `/usr/local/lib/node_modules/homebridge-music/scripts`.

Best copy `iTunes.applescript` to `MyScript.applescript` and open it (double click in the finder, or use `open MyScript.applescript` from the command line).  Change the `setPlayerOn` function to `play playlist t` instead of `play track t`.  Compile the script using `make MyScript.scpt` and specify `"script": "MyScript"` in config.json.
